= Braccio Library for Arduino =

The library offers easy access to the data from the onboard TinkerKit Braccio, and provides moves for the Braccio.

- Upgrades:
Soft-Start: Used with the Braccio Shield V4 create perform a soft start for the TinkerKit Braccio. It protects the servo motors and the junctions from damages

For more information about this library please visit us at
http://www.arduino.org/products/tinkerkit/17-arduino-tinkerkit/arduino-tinkerkit-braccio

== License ==

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
